### PR TITLE
validate all BSON types as of MongoDB v4.0

### PR DESCRIPTION
**Pull request by johndugan**

### CODE REVIEW

**Comment by matthew1534** [comment]
@johndugan I could be wrong but can't `int` also just be a normal integer for validation (i.e. not in object bson form)?

We have a scenario like this which works as we would expect it to:
```
{
  _id: {_bsontype: "ObjectID", id: Buffer(12)},
  my_int: 23
}
```

Think this might be the case for `long` and `double` too.

**Comment by BoLaMN** [comment]
agreed @matthew1534, 

cant just rely on the _bsonType and instead has to handle the automatic type casting mongo provides 

step in the right direction non the less, rebase it against the master and i will review/release when ready

cheers

**Comment by BoLaMN** [comment]
ive also added a checkBsomnType function so it doesnt get out of hand 

https://github.com/BoLaMN/ajv-bsontype/commit/13540ee0e38f916971744414b8eae4fc3b9463f3

**Comment by matthew1534** [comment]
@johndugan my forked master is now up to date so can either update here but maybe easier to open a PR directly on the repo: https://github.com/BoLaMN/ajv-bsontype

**Pull request closed without merging**
